### ISSUE TITLE
Questions regarding NGFW

### ISSUE THREAD

**Issue by ShreyasNBS** [PaloAltoNetworks/terraform-provider-cloudngfwaws#3]
Hi,

First of all thank you for this provider. 

I have a few questions: @shinmog @btorresgil @migara 

In the NGFW resource, I do not see an option to specify log settings. Is this meant to be done via the UI for now?
I understand that I will need an IAM role with Trust Account ID (Palo AWS Account that handles the firewall interaction), but that will merely grant firewall rights to push the logs to intended destination (for example, CloudWatch). 
https://docs.paloaltonetworks.com/cloud-ngfw/aws/cloud-ngfw-on-aws/create-cloud-ngfw-instances-and-endpoints/configure-logging-for-the-cloud-ngfw-on-aws.

Secondly, is there a way to programmatically add AWS Account to the NGFW? I forgot to download the CFT (Cloud Formation Stack) when I setup my account, but I was able to go into the CFTs in AWS Console later, and download the stack. At the bottom of the stack, there seems to be a message that is placed onto a SNS topic that informs Palo about the various ARN's for cross-account IAM roles. Can this be terraformed?

Thirdly, from what I can see, when I supply the log settings in CloudFormation (Cloudwatch, Kinesis firehose), from what I gather, those logging endpoints are only designated, but not actually created. Does this mean I will have to create a Cloudwatch Namespace/LogGroup and Kinesis Firehose before I can start using the Firewall?

That's a question too many, but it would be clarify a lot of things :)

Thanks,
Shreyas

**Comment by shinmog** [comment]
For the first question, yeah, it does seem like there should be a log settings resource.  I'll see if I can add this in.  When I do, I'll close out this github issue.

As for the second question, for programmatically adding AWS accounts, I think that it was decided that this should be a manual process.

For the third question, I actually don't know if the logging endpoint needs to exist before you can configure it as the logging endpoint.

**Comment by shinmog** [comment]
Ok, added log profile support.  Closing this issue out.

**Comment by shinmog** [comment]
@ShreyasNBS 

Make sure you update cloud-ngfw-aws-go as well, there are changes there that you'll need.

**Comment by ShreyasNBS** [comment]
Thanks @shinmog.
